### ISSUE TITLE
Bug: ImportError: cannot import name 'clock' from 'time' (unknown location)

### ISSUE THREAD

**Issue by felixmosh** [amir-zeldes/HebPipe#15]
I'm not able to run this lib with python v3.9

More info: https://github.com/PyTables/PyTables/issues/744

**Comment by amir-zeldes** [comment]
Thanks for reporting, this shouldn't be hard to fix

**Comment by amir-zeldes** [comment]
OK, this should be fixed in dev. A new master release should be coming soon, but you should be able to pull this, or just replace `lib/timing.py` if you don't want any of the latest experimental features.
