### ISSUE TITLE
No module named 'transformers.modeling_bert'

### ISSUE THREAD

**Issue by tamarjohn** [amir-zeldes/HebPipe#20]
Hi,
I'm trying to get POS annotation of a corpus using hebpipe/heb_pipe.py with this combination of parameters -wpl -o conllu 
and get this error message:
ModuleNotFoundError: No module named 'transformers.modeling_bert'

Do I need to upload anything else?
Thanks!

**Comment by amir-zeldes** [comment]
This is a duplicate of the just opened #19 - see discussion there, you may need to pip install transformers==3.5.1
